### ISSUE TITLE
Forecasting based on manual periods

### ISSUE THREAD

**Issue by bonddr** [alsabtay/ATAforecasting#1]
I am forecasting in 28-day intervals and converting the index to a yearweek() value, which returns all NA values. A yearmonth() identifier works but isn't possible with the groups I am using since some entries would have a duplicate date index. Here is an example of the code:

`date <- as.Date("2021-01-01")
test <- tibble(period = c(0:13),
       qty = rnorm(14, mean = 10),
       yw = yearweek(date %m+% days(28*period)),
       ym = yearmonth(date %m+% days(28*period)))`

Testing with yearweek:

`test %>% 
  as_tsibble(index = yw) %>% 
  model(ata = AutoATA(qty ~ trend("A"))) %>% 
  forecast(h = 1)`

Returns no values.

Testing with yearmonth:

`test %>% 
  as_tsibble(index = ym) %>% 
  model(ata = AutoATA(qty ~ trend("A"))) %>% 
  forecast(h = 1)`

Gives the error:
*Error: A valid tsibble must have distinct rows identified by key and index. i Please use `duplicates()` to check the duplicated rows.*

Please let me know if I am doing something wrong as I attempt to use this forecast model.

**Comment by alsabtay** [comment]
Thank you for your feedback. We fixed this issue but we are controlling bug fixes and other new addings. We update the codes on GitHub repo. We'll update the CRAN repo in few days. Could you forecast your data using the new version of the package? We're glad to hear any feedback on your analysis.

**Comment by bonddr** [comment]
I've installed the following:
`devtools::install_github("alsabtay/fable.ata")`

`devtools::install_github("alsabtay/ATAforecasting")`

I new get a new error but the same NA value returned using yearweek as the index:

*error encountered for ata [1] time column needs to be specified as the first date of the period*

**Comment by alsabtay** [comment]
We found a bug in 'fable.ata' package during converting 'tsibble' object to 'ts' object in terms of time variable. We fixed this issue. We update the codes on the GitHub repo. Could you forecast your data using the new version of the package (remotes::install_github("alsabtay/fable.ata")) ? 

We're glad to hear any feedback on your analysis.
